services:
  bot:
    container_name: couplecash_bot
    build: backend
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always
  db:
    container_name: couplecash_db
    image: postgres:17.0-alpine
    env_file:
      - ./.env
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
