"""empty message

Revision ID: 8234a8fc5995
Revises: c720ec7fa7c5
Create Date: 2024-11-11 15:25:03.647356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy_file.types
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8234a8fc5995'
down_revision: Union[str, None] = 'c720ec7fa7c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('receipt', sqlalchemy_file.types.ImageField(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'receipt')
    # ### end Alembic commands ###
