"""Add payment_type field to expenses table

Revision ID: c720ec7fa7c5
Revises: a5840a29f222
Create Date: 2024-09-28 00:26:50.941083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c720ec7fa7c5'
down_revision: Union[str, None] = 'a5840a29f222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('payment_type', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'payment_type')
    # ### end Alembic commands ###
